### ISSUE TITLE
How do I get a trial / eval copy of Hybris 

### ISSUE THREAD

**Issue by alberttwong** [prelegalwonder/hybris-docker#1]

**Comment by prelegalwonder** [comment]
You need to be a Hybris Partner of some sort. As an individual, if you're interested in doing work with Hybris, I'd recommend looking at the following link:

https://www.hybris.com/en/partners/partners-overview/contractor-partners/faq

If your company is considering Hybris, there is a Hybris Business Partner program. 

https://www.hybris.com/en/partners/become-a-partner

Once you're a partner, you can get access to the Hybris Wiki which has links to the media you can download.
